
LIB	=	rc3600

# Emulator relevant files
SRCS	+=	rc3600_emul.c

SRCS	+=	radix40.c
SRCS	+=	disass.c
SRCS	+=	disass_domus.c
SRCS	+=	domusobj.c

CFLAGS	+=	-I${.CURDIR}/../include

WARNS	?=	5

.include <bsd.lib.mk>
